### ISSUE TITLE
Animate Header Borders

### ISSUE THREAD

**Issue by mgschoen** [mgschoen/portfolio#15]
```CSS
.row.portfolio-header:before {
    content: "";
    position: absolute;
    width: 100%;
    height: 1px;
    background: rgba(0,0,0,.125);
    bottom: 0;
    transition: transform .4s ease-in-out;
    transform: scaleX(0);
}
.row.portfolio-header.sticky:before {
    transform: scaleX(1);
}
```
